[toolchain]
channel = "1.83.0"
components = [ "rustfmt", "rustc" ]
# Targets? Yes.
targets = [ 
    "arm-unknown-linux-gnueabi",  # roboRio
    "x86_64-pc-windows-msvc", # x64 windows
    "aarch64-pc-windows-msvc", # arm64 windows
    "x86_64-apple-darwin", # intel mac
    "aarch64-apple-darwin", # apple silicon
    "x86_64-unknown-linux-gnu", # x64 linux
    "aarch64-unknown-linux-gnu", # arm64 linux
    "arm-unknown-linux-gnueabihf", # arm32 linux
]
profile = "minimal"