[package]
name = "rdxusb-protocol"
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RdxUSB protocol definitions for Redux Robotics devices"
version = "0.1.1"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.1", features = ["derive"] }